name: Full Stack CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.changes.outputs.backend }}
      admin-frontend: ${{ steps.changes.outputs.admin-frontend }}
      customer-frontend: ${{ steps.changes.outputs.customer-frontend }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          backend:
            - 'backend/**'
          admin-frontend:
            - 'admin-frontend/**'
          customer-frontend:
            - 'customer-frontend/**'

  backend:
    needs: changes
    if: ${{ needs.changes.outputs.backend == 'true' }}
    uses: ./.github/workflows/backend-ci.yml

  admin-frontend:
    needs: changes
    if: ${{ needs.changes.outputs.admin-frontend == 'true' }}
    uses: ./.github/workflows/admin-frontend-ci.yml

  customer-frontend:
    needs: changes
    if: ${{ needs.changes.outputs.customer-frontend == 'true' }}
    uses: ./.github/workflows/customer-frontend-ci.yml

  integration:
    runs-on: ubuntu-latest
    needs: [backend, admin-frontend, customer-frontend]
    if: always() && (needs.backend.result == 'success' || needs.backend.result == 'skipped') && (needs.admin-frontend.result == 'success' || needs.admin-frontend.result == 'skipped') && (needs.customer-frontend.result == 'success' || needs.customer-frontend.result == 'skipped')
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Integration test placeholder
      run: |
        echo "All component tests passed successfully"
        echo "Ready for integration testing when components are implemented"