name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy'
        required: true
      confirm:
        description: 'Type "CONFIRM" to proceed with production deployment'
        required: true

jobs:
  validate:
    name: Validate Deployment Request
    runs-on: ubuntu-latest
    steps:
      - name: Check confirmation
        if: github.event.inputs.confirm != 'CONFIRM'
        run: |
          echo "Error: You must type CONFIRM to proceed with production deployment"
          exit 1
      
      - name: Check version format
        run: |
          if [[ ! ${{ github.event.inputs.version }} =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: Version must be in format X.Y.Z (e.g., 1.0.0)"
            exit 1
          fi
  
  prepare:
    name: Prepare Production Deployment
    needs: validate
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://multiprints.com
    outputs:
      version: ${{ github.event.inputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Create release tag
        run: |
          git tag v${{ github.event.inputs.version }}
          git push origin v${{ github.event.inputs.version }}
      
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          name: Release v${{ github.event.inputs.version }}
          tag_name: v${{ github.event.inputs.version }}
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  deploy-backend:
    name: Deploy Backend to Production
    needs: prepare
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://api.multiprints.com
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: v${{ needs.prepare.outputs.version }}
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Check if backend directory exists
        id: check_backend
        run: |
          if [ -d "backend" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Install dependencies
        if: steps.check_backend.outputs.exists == 'true'
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run migrations
        if: steps.check_backend.outputs.exists == 'true'
        working-directory: ./backend
        env:
          DATABASE_URL: ${{ secrets.PRODUCTION_DATABASE_URL }}
          FLASK_ENV: production
        run: |
          echo "Running database migrations..."
          # This would normally run migrations
          # flask db upgrade
      
      - name: Configure AWS credentials
        if: steps.check_backend.outputs.exists == 'true'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Deploy to AWS App Runner
        if: steps.check_backend.outputs.exists == 'true'
        run: |
          echo "Deploying backend version ${{ needs.prepare.outputs.version }} to AWS App Runner..."
          # This would normally deploy to AWS App Runner
          # aws apprunner update-service --service-arn ${{ secrets.PRODUCTION_BACKEND_SERVICE_ARN }} --source-configuration ...
      
      - name: Notify deployment status
        if: always()
        run: |
          if [ "${{ steps.check_backend.outputs.exists }}" == "false" ]; then
            echo "Backend directory does not exist yet, deployment skipped"
          elif [ "${{ job.status }}" == "success" ]; then
            echo "Backend deployment to production successful"
          else
            echo "Backend deployment to production failed"
            exit 1
          fi
  
  deploy-admin-frontend:
    name: Deploy Admin Frontend to Production
    needs: [prepare, deploy-backend]
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://admin.multiprints.com
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: v${{ needs.prepare.outputs.version }}
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Check if admin-frontend directory exists
        id: check_admin_frontend
        run: |
          if [ -d "admin-frontend" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Install dependencies
        if: steps.check_admin_frontend.outputs.exists == 'true'
        working-directory: ./admin-frontend
        run: npm ci
      
      - name: Build application
        if: steps.check_admin_frontend.outputs.exists == 'true'
        working-directory: ./admin-frontend
        env:
          NEXT_PUBLIC_API_URL: https://api.multiprints.com/api/v1
          NEXT_PUBLIC_VERSION: ${{ needs.prepare.outputs.version }}
        run: npm run build
      
      - name: Configure AWS credentials
        if: steps.check_admin_frontend.outputs.exists == 'true'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Deploy to AWS App Runner
        if: steps.check_admin_frontend.outputs.exists == 'true'
        run: |
          echo "Deploying admin frontend version ${{ needs.prepare.outputs.version }} to AWS App Runner..."
          # This would normally deploy to AWS App Runner
          # aws apprunner update-service --service-arn ${{ secrets.PRODUCTION_ADMIN_FRONTEND_SERVICE_ARN }} --source-configuration ...
      
      - name: Notify deployment status
        if: always()
        run: |
          if [ "${{ steps.check_admin_frontend.outputs.exists }}" == "false" ]; then
            echo "Admin frontend directory does not exist yet, deployment skipped"
          elif [ "${{ job.status }}" == "success" ]; then
            echo "Admin frontend deployment to production successful"
          else
            echo "Admin frontend deployment to production failed"
            exit 1
          fi
  
  deploy-customer-frontend:
    name: Deploy Customer Frontend to Production
    needs: [prepare, deploy-backend]
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://multiprints.com
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: v${{ needs.prepare.outputs.version }}
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Check if customer-frontend directory exists
        id: check_customer_frontend
        run: |
          if [ -d "customer-frontend" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Install dependencies
        if: steps.check_customer_frontend.outputs.exists == 'true'
        working-directory: ./customer-frontend
        run: npm ci
      
      - name: Build application
        if: steps.check_customer_frontend.outputs.exists == 'true'
        working-directory: ./customer-frontend
        env:
          NEXT_PUBLIC_API_URL: https://api.multiprints.com/api/v1
          NEXT_PUBLIC_VERSION: ${{ needs.prepare.outputs.version }}
        run: npm run build
      
      - name: Configure AWS credentials
        if: steps.check_customer_frontend.outputs.exists == 'true'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Deploy to AWS App Runner
        if: steps.check_customer_frontend.outputs.exists == 'true'
        run: |
          echo "Deploying customer frontend version ${{ needs.prepare.outputs.version }} to AWS App Runner..."
          # This would normally deploy to AWS App Runner
          # aws apprunner update-service --service-arn ${{ secrets.PRODUCTION_CUSTOMER_FRONTEND_SERVICE_ARN }} --source-configuration ...
      
      - name: Notify deployment status
        if: always()
        run: |
          if [ "${{ steps.check_customer_frontend.outputs.exists }}" == "false" ]; then
            echo "Customer frontend directory does not exist yet, deployment skipped"
          elif [ "${{ job.status }}" == "success" ]; then
            echo "Customer frontend deployment to production successful"
          else
            echo "Customer frontend deployment to production failed"
            exit 1
          fi
  
  post-deploy:
    name: Post-Deployment Tasks
    needs: [prepare, deploy-backend, deploy-admin-frontend, deploy-customer-frontend]
    runs-on: ubuntu-latest
    if: always() && needs.deploy-backend.result == 'success' && needs.deploy-admin-frontend.result == 'success' && needs.deploy-customer-frontend.result == 'success'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: v${{ needs.prepare.outputs.version }}
      
      - name: Run smoke tests
        run: |
          echo "Running smoke tests against production environment..."
          # This would normally run smoke tests against the production environment
          # ./scripts/run-smoke-tests.sh
      
      - name: Create deployment record
        run: |
          echo "Creating deployment record for version ${{ needs.prepare.outputs.version }}..."
          # This would normally create a deployment record
      
      - name: Send deployment notification
        run: |
          echo "Sending deployment notification..."
          # This would normally send a notification via Slack, email, etc.
          echo "Version ${{ needs.prepare.outputs.version }} has been deployed to production"
  
  rollback:
    name: Rollback on Failure
    needs: [prepare, deploy-backend, deploy-admin-frontend, deploy-customer-frontend]
    runs-on: ubuntu-latest
    if: failure() && (needs.deploy-backend.result == 'failure' || needs.deploy-admin-frontend.result == 'failure' || needs.deploy-customer-frontend.result == 'failure')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Rollback backend
        if: needs.deploy-backend.result == 'failure'
        run: |
          echo "Rolling back backend deployment..."
          # This would normally roll back to the previous version
          # aws apprunner start-deployment --service-arn ${{ secrets.PRODUCTION_BACKEND_SERVICE_ARN }} --deployment-id ${{ secrets.LAST_SUCCESSFUL_BACKEND_DEPLOYMENT }}
      
      - name: Rollback admin frontend
        if: needs.deploy-admin-frontend.result == 'failure'
        run: |
          echo "Rolling back admin frontend deployment..."
          # This would normally roll back to the previous version
          # aws apprunner start-deployment --service-arn ${{ secrets.PRODUCTION_ADMIN_FRONTEND_SERVICE_ARN }} --deployment-id ${{ secrets.LAST_SUCCESSFUL_ADMIN_FRONTEND_DEPLOYMENT }}
      
      - name: Rollback customer frontend
        if: needs.deploy-customer-frontend.result == 'failure'
        run: |
          echo "Rolling back customer frontend deployment..."
          # This would normally roll back to the previous version
          # aws apprunner start-deployment --service-arn ${{ secrets.PRODUCTION_CUSTOMER_FRONTEND_SERVICE_ARN }} --deployment-id ${{ secrets.LAST_SUCCESSFUL_CUSTOMER_FRONTEND_DEPLOYMENT }}
      
      - name: Send rollback notification
        run: |
          echo "Sending rollback notification..."
          # This would normally send a notification via Slack, email, etc.
          echo "Deployment of version ${{ needs.prepare.outputs.version }} to production failed and has been rolled back"